# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: Contributors by categories
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: contributors.categories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_contributors: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
              "🧩 Plugins / 🖼️ templates":["source/plugins/**", "source/templates/**"],
              "📚 Documentation":["README.md", "**/README.md", "**/metadata.yml"],
              "💻 Code (other)":["source/**", "Dockerfile"]
            }

      - name: Stargazers
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes

      - name: Compact display in base plugin
        uses: lowlighter/metrics@latest
        with:
          filename: plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes



      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_user: code-with-von
      

      # - uses: lowlighter/metrics@latest
      #   with:
      #     # Your GitHub token
      #     # The following scopes are required:
      #     #  - public_access (default scope)
      #     #  - read:user
      #     #  - read:org
      #     #  - public_repo
      #     #  - read:project
      #     # The following additional scopes may be required:
      #     #  - read:org      (for organization related metrics)
      #     #  - read:user     (for user related data)
      #     #  - read:packages (for some packages related data)
      #     #  - repo          (optional, if you want to include private repositories)
      #     token: ${{ secrets.METRICS_TOKEN }}

      #     # Options
      #     user: code-with-von
      #     template: classic
      #     base: header, activity, community, repositories, metadata
      #     commits_authoring: code-with-von
      #     config_display: large
      #     config_octicon: yes
      #     config_timezone: America/Fortaleza
      #     config_twemoji: yes
      #     plugin_achievements: yes
      #     plugin_achievements_display: compact
      #     plugin_achievements_secrets: yes
      #     plugin_achievements_threshold: X
      #     plugin_code: yes
      #     plugin_code_days: 3
      #     plugin_code_lines: 12
      #     plugin_code_load: 400
      #     plugin_code_visibility: public
      #     plugin_gists: yes
      #     plugin_isocalendar: yes
      #     plugin_isocalendar_duration: half-year
      #     plugin_leetcode: yes
      #     plugin_leetcode_limit_recent: 2
      #     plugin_leetcode_limit_skills: 10
      #     plugin_leetcode_sections: solved
      #     plugin_leetcode_user: code-with-von
      #     plugin_people: yes
      #     plugin_people_identicons: yes
      #     plugin_people_identicons_hide: yes
      #     plugin_people_limit: 24
      #     plugin_people_shuffle: yes
      #     plugin_people_size: 28
      #     plugin_people_types: followers, following
      #     plugin_projects: yes
      #     plugin_projects_descriptions: yes
      #     plugin_projects_limit: 4
      #     plugin_repositories: yes
      #     plugin_repositories_order: featured, pinned, starred, random
      #     plugin_repositories_pinned: 4
      #     plugin_repositories_starred: 4
      #     plugin_sponsors: yes
      #     plugin_sponsors_past: yes
      #     plugin_sponsors_sections: goal, list, about
      #     plugin_sponsors_size: 24
      #     plugin_sponsors_title: Sponsor Me!