name: Metrics
on:
  schedule: [{ cron: '0 * * * *' }]
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_isocalendar: yes

      - name: Starred
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: Stargazers
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_stargazers: yes

      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: America/Fortaleza

      - name: Followup
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_followup: yes
          plugin_followup_indepth: yes

      - name: Reactions
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage

      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/people.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_people: yes
          plugin_people_types: followers

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      - name: Snippet
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/snippet.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_code: yes
          plugin_code_load: 400

      - name: Detailed report
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/pagespeed.svg
          token: NOT_NEEDED
          base: ''
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://code-with-von.github.io

      - name: Lines
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1

      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          user: code-with-von
          filename: metrics/leetcode.svg
          token: NOT_NEEDED
          base: ''
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_user: code-with-von
